name: icons_launcher
description: A command-line tool which simplifies the task of updating your Flutter app's launcher icon. Full flexibility allows you to only update the launcher icon for specific platforms as needed.
version: 1.1.4
maintainer: Mrr Hak
homepage: https://github.com/mrrhak/icons_launcher

dependencies:
  args: ^2.3.0
  image: ^3.1.3
  path: ^1.8.0
  universal_io: ^2.0.4
  yaml: ^3.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.21.1
