name: icons_launcher
description: A command-line tool that simplifies the task of updating your Flutter app's launcher icon.
maintainer: Mrr Hak
homepage: https://mrrhak.com
repository: https://github.com/mrrhak/icons_launcher
version: 1.1.7

dependencies:
  args: ^2.3.0
  image: ^3.1.3
  path: ^1.8.0
  universal_io: ^2.0.4
  yaml: ^3.1.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.21.1
