name: Publish Package

on:
  release:
    types: [published]

jobs:
  publishing:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout'
        uses: actions/checkout@v3
        
      - name: '>> Dart package <<'
        uses: k-paxian/dart-package-publisher@master
        with:
          credentialJson: '${{ secrets.PUB_CREDENTIAL_JSON }}'
          format: true
          force: false
          suppressBuildRunner: false
          dryRunOnly: false
          skipTests: false